export const SHORTCUTS = [
  { key: 'Space / N', actionKey: 'nextPreset' },
  { key: 'P', actionKey: 'previousPreset' },
  { key: 'F / Double-click', actionKey: 'toggleFullscreen' },
  { key: 'A', actionKey: 'toggleAutopilot' },
  { key: 'S', actionKey: 'toggleFavorite' },
  { key: 'B', actionKey: 'toggleBlock' },
  { key: 'V', actionKey: 'togglePause' },
  { key: 'Q', actionKey: 'toggleQueue' },
  { key: 'K', actionKey: 'playPause' },
  { key: 'J', actionKey: 'previousTrack' },
  { key: 'L', actionKey: 'nextTrack' },
  { key: 'Escape', actionKey: 'closePanel' },
  { key: '? / H', actionKey: 'toggleShortcuts' },
];
